# .github/workflows/publish.yml

name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: './frontend/package-lock.json'
          node-version: '18'
      - run: npm install
        working-directory: ./frontend
      - run: npm run build
        working-directory: ./frontend
      - run: npx jsr publish
